[build]
  publish = "netlify_build_output"  # or wherever your React build output goes
  command = "npm run build"


[functions]
  directory = "../api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
