[build]
  publish = "netlify_build_output"
  command = "npm run build"
  functions = "api"

[functions]
  directory = "../api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
